spring:
  h2:
    console:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/gimmevibe-dev
    username: postgres
    password: postgres
  security:
    user:
      name:
      password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true

server:
  servlet:
    context-path: /api/v1

gimmevibe:
  app:
    SECRET:
    EXPIRATION_TIME: 900000
    TOKEN_PREFIX: Bearer
    HEADER_STRING: Authorization
    LOGIN_URL: /loginByUsingPOST
    SIGN_UP_URL: /saveNewUserByUsingPOST
